[package]
name = "rsky-pds"
version = "0.0.1"
authors = ["him@rudyfraser.com"]
description = "Rust reference implementation of an atproto PDS."
license = "Apache-2.0"
edition = "2021"
publish = false
homepage = "https://github.com/blacksky-algorithms/rsky"
repository = "https://github.com/blacksky-algorithms/rsky/tree/main/rsky-pds"
documentation = "https://docs.rs/rsky-pds"

[dependencies]
rocket = { version = "=0.5.0-rc.3", features = ["json"] }
dotenvy = "0.15"
rsky-lexicon = { path = "../rsky-lexicon", version = "0.1.0" }
diesel = { version = "2.1.0", features = ["postgres"] }
chrono = "0.4.26"
serde = { version = "1.0.160", features = ["derive"] }
serde_derive = "^1.0"

[dependencies.rocket_sync_db_pools]
version = "=0.1.0-rc.3"
features = ["diesel_postgres_pool"]